version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel_user
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
