services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: petmatch_app
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - petmatch-network

    nginx:
        image: nginx:alpine
        container_name: petmatch_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - petmatch-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: petmatch_db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - petmatch-network

networks:
    petmatch-network:
        driver: bridge
        name: petmatch-network

volumes:
    dbdata:
